Feat/rf17 consultar perfil
Black-Dot-2024/Zeitgeist-Backend pull request #102
Opened 2024-04-27 00:01 UTC by sebFlores02

## Pull Request Titulo

RF17/ConsultarPerfil: Consultar Perfil de cliente único

### Descripción

Este requisito permite visualizar la información detallada o perfil de un cliente en especifico al clic en su tarjeta en consultar todos los clientes.

### Cambios realizados

- schema.prisma
- company.entity.ts
- company.controller.ts
- company.routes.ts
- company.service.ts
- company-entity-from-db-model.mapper.ts
- company.repository.ts

### Story Points

5

### Criterios de aceptación

El sistema muestra la siguiente información de la empresa:
- [x] Nombre
- [x] Correo electrónico
- [x] Cel/Tel
- [x] Fecha de constitución
- [x] Domicilio Fiscal

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

2024-04-27 00:12 UTC, DHurtado714-itesm requested changes

2024-04-27 00:12 UTC, DHurtado714-itesm commented on src/api/controllers/company.controller.ts
No hay zod validator

2024-04-27 00:12 UTC, DHurtado714-itesm commented on src/api/routes/company.routes.ts
> + */
open api esta deprecado

2024-04-27 00:12 UTC, DHurtado714-itesm commented on src/core/app/services/company.service.ts
> +    console.log(error);
no incluir el console.log

2024-04-27 00:12 UTC, DHurtado714-itesm commented on src/core/app/services/company.service.ts
>      console.log(error);
borrar el console.log aunque no sea tuyo

2024-04-27 00:12 UTC, DHurtado714-itesm commented on src/core/app/services/company.service.ts
> +    throw new Error('an unexpected error occurred');
Dar un error mas especifico y no es necesario el try catch si solo es consultar

2024-04-27 00:12 UTC, DHurtado714-itesm commented on src/core/domain/entities/project.entity.ts
> + *
Cambiar a ingles

2024-04-27 18:29 UTC, salgue441 approved these changes

2024-04-27 18:29 UTC, salgue441 commented on src/api/routes/company.routes.ts
> +router.get('/:id', CompanyController.getUnique);
Falta el middleware de auth

2024-04-27 18:30 UTC, salgue441 requested changes
Del comentario anterior xD

2024-04-27 20:15 UTC, DHurtado714-itesm requested changes

2024-04-27 20:15 UTC, DHurtado714-itesm commented on src/api/controllers/company.controller.ts
> +});
Usar string().uuid()

2024-04-27 20:15 UTC, DHurtado714-itesm commented on src/api/routes/company.routes.ts
> +router.get('/:id', CompanyController.getUnique);
y de RBAC

2024-04-27 20:15 UTC, DHurtado714-itesm commented on src/index.ts
> +    origin: 'http: //localhost:300' || CLIENT_URL,
Esto no deberia de ir, aparte dice 300

2024-04-28 03:00 UTC, OlimpiaGarcia commented
Error: src/api/routes/company.routes.ts(13,33): error TS2339: Property 'CONTABLE' does not exist on type 'typeof SupportedRoles'.

no compila :(

2024-04-28 18:13 UTC, DHurtado714-itesm commented
Revisa bien los comments

2024-04-28 19:29 UTC, sebFlores02 commented
> Revisa bien los comments

oops, se me paso cambiar lo del validator. Ya lo cambie, creo que seria todos los cambios que pidieron.

2024-04-28 20:03 UTC, salgue441 approved these changes

2024-04-28 23:55 UTC, DHurtado714-itesm approved these changes

2024-04-28 23:55 UTC, merged