Feat/rf 16 project details
Black-Dot-2024/Zeitgeist-Backend pull request #136
Opened 2024-04-30 02:22 UTC by DenisseDB

## Project Details

[16]: Project Details

### Descripción

Feature para con el link del proyecto, obtener su información, obteniendo el idCompany para de igual manera obtener el name de la misma 

### Cambios realizados

- Controller = getProjectById
- Routes = '/details/:id'
- Service = getProjectById
- Project-details.service.test

### Story Points

5

### Pruebas
Obtener la info del proyecto dando el id
Obtener la info del proyecto y el nombre del cliente mandado id de proyecto y id de company

![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/80787054/5ff3a2ad-4628-47ca-a7ce-4c94197ad385)

### Criterios de aceptación

-El sistema deberá mostrar la información relacionada a este proyecto.

- La información que el usuario puede visualizar del proyecto incluye:
- Nombre del proyecto
- Descripción
- Cliente
- Matter
- Categoría
- Fecha de finalización
- Fecha de Inicio
- Cobrable
- Periódico
- Área (legal/accountable)

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

2024-04-30 16:40 UTC, dembA7 requested changes

2024-04-30 16:40 UTC, dembA7 commented on src/api/controllers/project.controller.ts
> +async function getProjectById(req: Request, res: Response) {
Falta documentar función

2024-04-30 16:40 UTC, dembA7 commented on src/api/routes/project.routes.ts
> +router.get(
descomentar middlewares

2024-04-30 16:40 UTC, dembA7 commented on src/core/app/services/__tests__/company.servicec.test.ts
está mal el nombre del archivo, por qué se cambió?

2024-04-30 16:40 UTC, dembA7 commented on src/core/app/services/__tests__/project-details.service.test.ts
estas pruebas deberían ir en project.service.test.ts

2024-04-30 16:40 UTC, dembA7 commented on .github/actions/develop.yml
qué son estos cambios de actions?

2024-04-30 17:34 UTC, DenisseDB commented on src/core/app/services/__tests__/company.servicec.test.ts
ya tenia ese nombre, intente cambiarlo pero ya existe otro test con el nombre "company.service.test.ts"

2024-04-30 17:53 UTC, DenisseDB commented on src/core/app/services/__tests__/project-details.service.test.ts
Listo

2024-04-30 18:02 UTC, DenisseDB commented on src/core/app/services/__tests__/project-details.service.test.ts
![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/80787054/aea06e18-a0e3-41c1-a59a-1801e7375207)

2024-04-30 22:15 UTC, DenisseDB commented on .github/actions/develop.yml
Ya se borro la carpeta

2024-05-01 02:45 UTC, dembA7 requested changes

2024-05-01 02:45 UTC, dembA7 commented on src/core/app/services/__tests__/company.servicec.test.ts
borra el archivo pls

2024-05-01 02:45 UTC, dembA7 commented on src/core/app/services/__tests__/project-details.service.test.ts
me refiero a que tus pruebas deben ir en el archivo __tests__/project.service.test.ts porque estás probando funcionalidades del servicio de project.

2024-05-01 03:07 UTC, dembA7 approved these changes

2024-05-01 03:08 UTC, merged