Fix/projects
Black-Dot-2024/Zeitgeist-Backend pull request #169
Opened 2024-05-09 21:03 UTC by sgarnica1

Order projects by status

2024-05-09 21:04 UTC, ArmandoRosasB submitted a review, later dismissed

2024-05-10 00:23 UTC, DHurtado714-itesm requested changes

2024-05-10 00:23 UTC, DHurtado714-itesm commented on src/core/infra/repositories/project.repository.ts
> +      else 11
Se puede evitar usar el SQL?

2024-05-10 00:23 UTC, DHurtado714-itesm commented on src/core/infra/repositories/project.repository.ts
> +    console.log(data);
No deberia de tener un console.log

2024-05-10 20:50 UTC, lCDSLl-Richard requested changes

2024-05-10 20:50 UTC, lCDSLl-Richard commented on src/core/infra/repositories/project.repository.ts
> +      });
Si vamos a usar el SQL para ordenar los status, habría que eliminar la parte en la que se hace una query para los que no están en done y una query para los que sí. Se tendría que hacer una sola query como la de arriba.

2024-05-11 19:47 UTC, sgarnica1 commented on src/core/infra/repositories/project.repository.ts
> +      else 11
Se eliminó esta función

2024-05-11 20:45 UTC, DHurtado714-itesm approved these changes

2024-05-11 21:16 UTC, dembA7 requested changes

2024-05-11 21:16 UTC, dembA7 commented on src/core/infra/repositories/employee.repository.ts
> +    console.log(error);
quitar console.log

2024-05-11 21:36 UTC, dembA7 approved these changes

2024-05-11 22:15 UTC, lCDSLl-Richard approved these changes

2024-05-11 22:15 UTC, merged