Feat/rf06 send task email
Black-Dot-2024/Zeitgeist-Backend pull request #208
Opened 2024-05-24 06:09 UTC by DHurtado714-itesm

## Pull Request Titulo

[Feature/RF06]: Enviar notificacion cuando se crea una tarea

### Descripción

Se implemento un sistema para enviar notificaciones por correo electronico. Se envia cuando se crea una tarea, excepto cuando se auto asigna una tarea.

### Cambios realizados

- Implementar Resend para enviar notificaciones por correo
- Añadir template para notificar los correos
- 

### Story Points

5

### Pruebas

Incluye prueba unitaria
- Matriz de caso de prueba https://docs.google.com/spreadsheets/d/1usJCZY3vorQVCezzWEK3mijFIfOdi-UEw1q1pUB-_oU/edit#gid=393691759

### Criterios de aceptación

[x] Si un usuario es asignado a una tarea, el sistema manda una notificación por correo al usuario  al que se asignó la tarea.
[ ] El usuario recibe en la notificación el nombre de la tarea y el proyecto al que pertenece esa nueva tarea.

### Dependencias

- Necesitamos verificar el dominio. En progreso

### Definición de Done

- [ ] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [ ] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [ ] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [ ] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screen de pruebas y/o notas

Cualquier información adicional que el revisor o el autor del PR necesite saber. Aquí es donde se puede incluir imagenes, gifs, etc.

2024-05-24 07:00 UTC, dembA7 requested changes
puedes mandarlo a la rama de mbi pls

2024-05-25 01:24 UTC, lCDSLl-Richard approved these changes

2024-05-25 01:28 UTC, Ian326 approved these changes

2024-05-25 01:49 UTC, dembA7 approved these changes

2024-05-25 01:50 UTC, merged