Feat/rf23 eliminar cliente
Black-Dot-2024/Zeitgeist-Backend pull request #222
Opened 2024-05-25 21:01 UTC by DiegoPerdomoS

## Pull Request Titulo

[Eliminar Cliente/RF23]: Eliminar un cliente

### Descripción

El administrador es capaz de eliminar un cliente, luego se borra cualquier proyecto asociado con ese cliente, y por ultimo las tareas asociadas a ese proyecto

### Cambios realizados

- prisma/migrations/20240524224602_delete_company_constraints/migration.sql
- prisma/schema.prisma
- src/api/controllers/company.controller.ts
- src/api/routes/company.routes.ts
- src/core/app/services/company.service.ts
- src/core/infra/repositories/company.repository.ts
- src/core/app/services/__tests__/company.service.test.ts

### Story Points

2 por la US completa

### Pruebas

Integración:
https://docs.google.com/spreadsheets/d/1usJCZY3vorQVCezzWEK3mijFIfOdi-UEw1q1pUB-_oU/edit#gid=867339813

Unitarias:
- Verifica RBAC
- Eliminar el cliente si es admin
- Compañia no existe

### Criterios de aceptación

- [ ] El sistema permite al administrador buscar clientes por nombre para seleccionarlas para la baja.
- [ ] El usuario ingresa al detalle del cliente desea eliminar.
- [ ] Al seleccionar el ícono de borrar, el sistema muestra una pantalla de confirmación antes de proceder.
- [ ] Una vez confirmada la baja, el sistema elimina el cliente y todas las relaciones con otras entidades de la plataforma (incluyendo los proyectos que pertenecían al cliente).
- [ ] El sistema proporciona una confirmación visual en la plataforma de que el cliente ha sido dado de baja correctamente.
- [ ] El sistema redirige a la vista de todos los clientes.

### Dependencias

No tengo dependencias

### Definición de Done

- [ ] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [ ] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [ ] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [ ] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screen de pruebas y/o notas

<img width="493" alt="Screenshot 2024-05-25 at 3 00 48 p m" src="https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/161071886/53a8bb34-7568-4dd3-90fa-d8d814606742">

2024-05-27 23:28 UTC, lCDSLl-Richard commented on src/api/controllers/company.controller.ts
>    id: z.string().uuid().min(1, { message: 'clientId cannot be empty' }),
Con el `.uuid()` ya no necesitas la condición del min.

2024-05-27 23:30 UTC, lCDSLl-Richard commented on src/api/controllers/company.controller.ts
> +    const { id } = idSchema.parse({ id: req.params.id });
En lugar de hacer ese schema, podrías simplemente hacer:
```typescript
const id = z.string().uuid().parse(req.params.id)
```

2024-05-27 23:31 UTC, lCDSLl-Richard commented on src/core/app/services/company.service.ts
> +    const role = await RoleRepository.findByEmail(email);
Por qué se checa el rol en el servicio en lugar de con el middleware en la ruta?

2024-05-27 23:56 UTC, lCDSLl-Richard requested changes

2024-05-27 23:56 UTC, lCDSLl-Richard commented on src/api/routes/company.routes.ts
> +router.delete('/delete/:id', CompanyController.deleteCompany, checkAuthRole([SupportedRoles.ADMIN]));
Debería de ser al revés,
```typescript
router.delete('/delete/:id', checkAuthRole([SupportedRoles.ADMIN]), CompanyController.deleteCompany)
```

2024-05-28 01:05 UTC, lCDSLl-Richard approved these changes

2024-05-28 01:06 UTC, ArmandoRosasB approved these changes

2024-05-28 17:08 UTC, sgarnica1 submitted a review, later dismissed

2024-05-28 18:27 UTC, Ian326 requested changes

2024-05-28 18:27 UTC, Ian326 commented on src/api/controllers/company.controller.ts
> +      res.status(403).json({ message: 'Internal server error occurred.' });
cambia el mensaje de error. El que usamos en expenses es: 'Unauthorized employee'

2024-05-28 18:27 UTC, Ian326 commented on src/core/app/services/company.service.ts
> +    console.log(role);
borra este console.log

2024-05-28 18:27 UTC, Ian326 commented on src/core/infra/repositories/company.repository.ts
> +    console.error(error);
borra este console.error

2024-05-28 18:58 UTC, sgarnica1 submitted a review, later dismissed

2024-05-28 19:03 UTC, Ian326 approved these changes

2024-05-28 20:15 UTC, lCDSLl-Richard requested changes

2024-05-28 20:15 UTC, lCDSLl-Richard commented on src/core/app/services/company.service.ts
> +    }
Todo este check ya no es necesario con el middleware

2024-05-28 21:46 UTC, ArmandoRosasB approved these changes

2024-05-28 21:50 UTC, Ian326 approved these changes

2024-05-28 21:51 UTC, RamonaNF approved these changes

2024-05-28 21:51 UTC, merged