Fix/tasks date
Black-Dot-2024/Zeitgeist-Backend pull request #225
Opened 2024-05-27 23:11 UTC by sgarnica1

## Tasks/RF25-ID030, ID031 Fechas posteriores al fin del proyecto

### Descripción

El sistema permitía al usuario ingresar una fecha de finalización de una tarea posterior a la fecha de finalización de un proyecto. Se corrigió para no permitir este comportamiento

### Issues

- Tasks/RF25-ID030, ID031 Fechas posteriores al fin del proyecto

### Cambios realizados

- El sistema no permite al usuario crear o modificar una tarea con una fecha de finalización mayor a la fecha de finalización del proyecto a la que pertenece

### ScreenShot / Video

![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/3cf307a6-6ef6-449a-a528-fd0aa0415997)

2024-05-27 23:26 UTC, DiegoPerdomoS submitted a review, later dismissed

2024-05-27 23:26 UTC, lCDSLl-Richard requested changes
Habría que hacer esta validación en el front también para mejor consistencia en la UX.

2024-05-27 23:26 UTC, lCDSLl-Richard commented on src/utils/methods.ts
> +  if (date1 == undefined || date1 == null || date2 == undefined || date2 == null) throw new Error('Missing date');
Esta condición se puede cambiar por `!date1 || !date2`.

2024-05-27 23:39 UTC, lCDSLl-Richard approved these changes

2024-05-27 23:58 UTC, DiegoPerdomoS approved these changes

2024-05-28 00:04 UTC, Ian326 approved these changes

2024-05-28 00:05 UTC, merged