Feat/rf31 notificacion entre areas
Black-Dot-2024/Zeitgeist-Backend pull request #231
Opened 2024-05-29 00:48 UTC by DHurtado714-itesm

## Pull Request Titulo

[Feature/Task ID]: Descripción del cambio

### Descripción

Descripción clara y concisa de los cambios realizados. Incluye el contexto relevante, como historias de usuario o criterios de aceptación.

### Cambios realizados

- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.

### Story Points

Estima la complejidad de la tarea en puntos de historia.

### Pruebas

Describe la prueba unitaria de pruebas utilizada para este cambio. Incluye detalles sobre pruebas unitarias, pruebas de integración, pruebas de aceptación y cualquier manual realizado.

### Criterios de aceptación

Describe los criterios que deben cumplirse para que este PR sea aceptado. Esto debe estar alineado con la historia de usuario o tarea original.

### Dependencias

Enumera cualquier dependencia o PR relacionado que deba fusionarse antes o después de este PR.

### Definición de Done

- [ ] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [ ] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [ ] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [ ] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screen de pruebas y/o notas

Cualquier información adicional que el revisor o el autor del PR necesite saber. Aquí es donde se puede incluir imagenes, gifs, etc.

2024-06-03 20:12 UTC, sgarnica1 requested changes

2024-06-03 20:12 UTC, sgarnica1 commented on src/core/app/services/employee.service.ts
> +async function getAllEmployeesByDepartment(department: SupportedDepartments): Promise<EmployeeEntity[]> {
Como sugerencia, no debería envolverse en un bloque try catch para manejo de errores?

2024-06-03 20:12 UTC, sgarnica1 commented on src/core/app/services/notification.service.ts
> +  const response = await EmailProvider.sendEmail(emailList, subject, body);
De igual manera, no debería envolverse en un bloque try catch para manejo de errores?

2024-06-03 20:38 UTC, DHurtado714-itesm commented on src/core/app/services/employee.service.ts
> +async function getAllEmployeesByDepartment(department: SupportedDepartments): Promise<EmployeeEntity[]> {
La capa inferior de repository no arroja esos errores. En dado caso que ocurra algo con la DB se llama ese error especifico. Seria bueno tenerlo en n try catch, si se llegara a hacer logica interna

2024-06-03 20:38 UTC, DHurtado714-itesm commented on src/core/app/services/notification.service.ts
> +  const response = await EmailProvider.sendEmail(emailList, subject, body);
mismo comment

2024-06-04 00:28 UTC, ArmandoRosasB approved these changes

2024-06-04 00:29 UTC, RamonaNF approved these changes

2024-06-04 00:45 UTC, DiegoPerdomoS approved these changes

2024-06-04 01:01 UTC, merged