feat/RF40 modificar estatus viatico
Black-Dot-2024/Zeitgeist-Backend pull request #233
Opened 2024-05-29 19:29 UTC by sgarnica1

## RF40 Modificar Estatus de un Viatico

[Feature/Task ID]: RF40 Modificar Estatus de un Viatico

### Descripción

El sistema permite al usuario (admin y contable) actualizar el estatus de un reporte de viático y subir un comprobante de pago como link de Google Drive

### Cambios realizados

- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.

### Story Points

8

### Pruebas

Pruebas unitarias para: 
- Verificar que un viático se actualice de manera correcta
- Verificar que el estatus es válido
- Verificar que se actualiza correctamente el enlace del comprobante
![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/71858836/dfb9430a-a846-4ae9-b52e-1a0c3cd371be)

### Criterios de aceptación

- Al ingresar al detalle de un reporte (RF32), el sistema muestra la opción de cambiar el status  (Paid, Accepted, Rejected, Pending).
- Al cambiar el estatus a “Payed”, el sistema permite subir un link de Google Drive para mandar el comprobante de que ya fue pagado.
- El sistema solicita al usuario reconfirmar su acción antes de subir el link
- En el detalle de un reporte ahora se muestra el link a esa factura (visible para todos)

### Dependencias

RF32 Consultar detalles de reporte de viatico

### Definición de Done

- [ ] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [ ] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [ ] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [ ] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screen de pruebas y/o notas

![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/71858836/db9d1ff8-0a60-4dd2-aa66-f3a40170af5e)

2024-05-29 19:38 UTC, Ian326 approved these changes
LGTM! 👍

2024-05-29 21:35 UTC, lCDSLl-Richard requested changes

2024-05-29 21:35 UTC, lCDSLl-Richard commented on src/api/controllers/expense.controller.ts
No sería mejor tener un endpoint genérico de `expense` que reciba cualquier campo y lo actualice en uno ya existente?

2024-05-29 22:31 UTC, sgarnica1 commented on src/api/controllers/expense.controller.ts
Fue justo parte de la conversación que tuvimos ayer Ian y yo, pero como sólo se actaulizarán estos campos, se crearon solo estos endpoints para evitar hacer validaciones adicionales

2024-05-30 20:48 UTC, lCDSLl-Richard approved these changes

2024-05-30 20:52 UTC, DiegoPerdomoS approved these changes

2024-05-30 20:52 UTC, merged