Feat/rf35 eliminar reportede viatico
Black-Dot-2024/Zeitgeist-Backend pull request #234
Opened 2024-05-30 21:24 UTC by yna2131

## Pull Request Titulo

[Feat/RF35]: Eliminar un reporte de viático

### Descripción

Se realizó el backend para el requisito funcional 35, eliminar un reporte de viático. 

### Cambios realizados

- expense.routes.ts
- expense.controller.ts
- expense.service.ts
- expense.repository.ts
- expense.service.test.ts

### Story Points

2

### Pruebas

![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105308046/2e573b70-7754-4b3d-8286-5d01fc5a77f5)

### Criterios de aceptación

- [ ] Al ingresar al detalle de un reporte  (RF32), el sistema muestra la opción de eliminar el reporte
- [ ] Al seleccionar la opción, el sistema muestra un modal de confirmación donde el usuario puede decidir si eliminarlo o no
- [ ] Si se selecciona la opción de eliminar, el sistema manda un mensaje de éxito o error según sea el caso
- [ ] En caso de seleccionar cancelar eliminación, el modal se cierra y no se elimina el reporte

### Dependencias

- RF32: Consultar detalle de un reporte de viático

### Definición de Done

- [ ] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [ ] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [x] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [x] La documentación ha sido actualizada (si corresponde).
- [x] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [x] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [x] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screen de pruebas y/o notas

![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105308046/be1bb28d-905f-4313-aa92-c7f7b273ce8e)

2024-05-31 22:50 UTC, DHurtado714-itesm requested changes

2024-05-31 22:50 UTC, DHurtado714-itesm commented on src/api/controllers/expense.controller.ts
> +}
Usa Zod para validar que sea un uuid valido

2024-05-31 22:50 UTC, DHurtado714-itesm commented on src/core/infra/repositories/expense.repository.ts
> +async function deleteExpenseReport(reportId: string): Promise<ExpenseReport> {
cambialo a `deleteReport`

2024-06-01 06:45 UTC, lCDSLl-Richard approved these changes

2024-06-02 16:06 UTC, DHurtado714-itesm approved these changes

2024-06-02 16:06 UTC, DHurtado714-itesm requested changes

2024-06-02 16:06 UTC, DHurtado714-itesm commented on .github/ISSUE_TEMPLATE/issue-de-defecto.md
Adistaste el issue template, esto afecta a los demas

2024-06-04 05:16 UTC, dembA7 requested changes

2024-06-04 05:16 UTC, dembA7 commented on prisma/schema.prisma
> +  provider        = "prisma-client-js"
este tab va aquí?

2024-06-04 05:16 UTC, dembA7 commented on src/api/routes/expense.routes.ts
> +router.delete('/report/delete/:id', ExpenseController.deleteReport);
cualquier empleado puede borrar el reporte? ahorita está para que pueda borrarlo admin, legal y contable

2024-06-04 05:16 UTC, dembA7 commented on src/core/app/services/__tests__/expense.service.test.ts
> +    it('Should throw an error if expense report is not deleted', async () => {
faltaría la prueba para cuando el expense report se deletea con éxito no?

2024-06-04 05:16 UTC, dembA7 commented on src/core/infra/repositories/expense.repository.ts
> +    console.log(error);
quitar console.log

2024-06-04 05:24 UTC, yna2131 commented on src/api/routes/expense.routes.ts
> +router.delete('/report/delete/:id', ExpenseController.deleteReport);
Sí, tú puedes borrar tu propio reporte. Y el admin y contable el de todos

2024-06-04 05:26 UTC, yna2131 commented on src/core/app/services/__tests__/expense.service.test.ts
> +    it('Should throw an error if expense report is not deleted', async () => {
La verdad pensé que con ese caso ya estamos verificando que el código funciona como esperado

2024-06-04 05:28 UTC, dembA7 commented on src/api/routes/expense.routes.ts
> +router.delete('/report/delete/:id', ExpenseController.deleteReport);
pero ahí estás dejando que todos los de legal borren todos los reportes, tendrías que hacer una validación en el servicio del empleado asociado al reporte, si el empleado del reporte es el mismo que hace la request entonces te deja borrarlo

2024-06-04 05:28 UTC, dembA7 commented on src/core/app/services/__tests__/expense.service.test.ts
> +    it('Should throw an error if expense report is not deleted', async () => {
igual mejor crear la prueba unitaria pls

2024-06-04 05:35 UTC, yna2131 commented on src/api/routes/expense.routes.ts
> +router.delete('/report/delete/:id', ExpenseController.deleteReport);
Pero eso de está limitando desde la parte de consultar. Los de legal no pueden consultar los reportes de los demás. Entonces pueden borrar sus propios reportes

2024-06-04 05:42 UTC, dembA7 commented on src/api/routes/expense.routes.ts
> +router.delete('/report/delete/:id', ExpenseController.deleteReport);
ah okey está bien entonces

2024-06-04 05:57 UTC, yna2131 commented on prisma/schema.prisma
> +  provider        = "prisma-client-js"
![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105308046/c82539f0-388d-4aa8-8fdb-e181d73861eb)

Creo que lo tiene por el formateador. Lo quito?

2024-06-04 06:06 UTC, dembA7 approved these changes

2024-06-04 15:47 UTC, sgarnica1 approved these changes

2024-06-04 16:09 UTC, DHurtado714-itesm approved these changes

2024-06-04 16:09 UTC, merged