RF29: Create Expense Report
Black-Dot-2024/Zeitgeist-Backend pull request #235
Opened 2024-05-31 02:19 UTC by dembA7

## RF29: Create Expense Report

[RF29]: Descripción del cambio

### Descripción

Se agregó endpoint de creación de reporte de viático. Recibe los atributos del reporte, y los gastos del reporte en un arreglo.

### Cambios realizados

- Se modificó el archivo ´´´prisma/schema.prisma´´´
- Se modificó el archivo ´´´src/api/routes/expense.routes.ts´´´
- Se modificó el archivo ´´´src/api/controllers/expense.controller.ts´´´
- Se modificó el archivo ´´´src/core/app/services/expense.service.ts´´´
- Se modificó el archivo ´´´src/core/app/services/__tests__/expense.service.test.ts´´´
- Se modificó el archivo ´´´src/core/infra/repositories/expense.repository.ts´´´
- Se modificó el archivo ´´´src/core/domain/entities/expense.entity.ts´´´
- Se modificó el archivo ´´´src/core/infra/mappers/expense-entity-from-db-model.mapper.ts´´´

### Story Points

13

### Pruebas

Se construyeron las pruebas unitarias necesarias para comprobar el correcto funcionamiento de este requerimiento.

![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/93755653/c08e6afb-d285-48ac-ad0f-acdea0ecc7bb)

### Criterios de aceptación

- [ ] Al consultar el historial de viáticos  (RF26), el sistema muestra una opción para registrar un nuevo reporte.
- [ ] El sistema redirige al usuario a un formulario donde puede ingresar la siguiente información:
- [ ] Título del reporte de viáticos (“Reason for Expense”). 
- [ ] Fecha de creación del reporte (“Date”)
- [ ] Los gastos que pertenecen al reporte:
    - [ ] Fecha
    - [ ] Proveedor
    - [ ] Descripción
    - [ ] Link de drive de la factura (Debe funcionar como hipervínculo si el valor inicia con HTTP)
    - [ ] Importe
- [ ] El sistema muestra la opción de agregar otro gasto.
- [ ] El sistema limita la cantidad de gastos que se puedan crear en un reporte a una cantidad de máximo 30 ítems.
- [ ] El sistema asigna el status “Pending” por defecto al reporte.
- [ ] El sistema asigna el reporte al empleado que lo haya creado.

### Dependencias

N/A.

### Definición de Done

- [ ] La tarea ha sido completamente implementada, cumpliendo con todos los requisitos y funcionalidades definidos.
- [ ] Todas las pruebas pasan, siguiendo el plan de pruebas.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Se han cerrado todos los issues (si aplicara) creados en el defect Log.
- [ ] Se ha creado o actualizado la documentación necesaria relacionada con la tarea.
- [ ] Se ha mapeado en las herramientas de trazabilidad [RTM](https://docs.google.com/spreadsheets/d/1Dqh-fTPP5tEfbQ_cVwz-jI74CmAe0DkSAw2a-vVrbVk/edit?usp=sharing), [PVG](https://docs.google.com/spreadsheets/d/1mFO9Bb7gJysk4sDaJ2z7ufl0epSR40XKp3J-r4IxFVc/edit#gid=1369995251)

### Screen de pruebas y/o notas

N/A

2024-06-02 16:10 UTC, DHurtado714-itesm requested changes

2024-06-02 16:10 UTC, DHurtado714-itesm commented on src/api/routes/expense.routes.ts
Revisa bien las acciones segun el rol de usuario

2024-06-03 01:47 UTC, Ian326 submitted a review, later dismissed

2024-06-03 01:48 UTC, Ian326 commented
MBI no sirve en 'Expenses' hasta que esto esté mergeado :/

2024-06-03 18:21 UTC, dembA7 commented on src/api/routes/expense.routes.ts
corregido, gracias

2024-06-03 18:25 UTC, DiegoPerdomoS approved these changes

2024-06-03 20:00 UTC, ArmandoRosasB approved these changes

2024-06-03 21:16 UTC, Ian326 approved these changes

2024-06-03 21:51 UTC, merged