fix(RF12): Add get unarchived companies endpoint
Black-Dot-2024/Zeitgeist-Backend pull request #246
Opened 2024-06-05 19:51 UTC by dembA7

## fix(RF12): Add get unarchived companies endpoint

[RF12]: Add get unarchived companies endpoint

### Descripción

Se agregó un endpoint que devuelve únicamente los clientes que NO estén archivados.

### Cambios realizados

- Se modificó el archivo ```src/api/controllers/company.controller.ts```
- Se modificó el archivo ```src/api/routes/company.routes.ts```
- Se modificó el archivo ```src/api/validators/company.validator.ts```
- Se modificó el archivo ```src/core/app/services/company.service.ts```
- Se modificó el archivo ```src/core/infra/repositories/company.repository.ts```

### Screen de pruebas y/o notas

N/A

2024-06-05 20:40 UTC, ArmandoRosasB requested changes

2024-06-05 20:40 UTC, ArmandoRosasB commented on src/core/infra/repositories/company.repository.ts
> +    const data: Array<any> = await Prisma.$queryRaw`
Tipar un arreglo con 'any' no podria llegar a causar problemas?

2024-06-05 23:19 UTC, dembA7 commented on src/core/infra/repositories/company.repository.ts
> +    const data: Array<any> = await Prisma.$queryRaw`
mb no me di cuenta de los tipos, ya lo corrijo

2024-06-05 23:48 UTC, ArmandoRosasB approved these changes

2024-06-06 01:21 UTC, Ian326 approved these changes

2024-06-06 01:22 UTC, RamonaNF approved these changes

2024-06-06 01:22 UTC, OlimpiaGarcia approved these changes

2024-06-06 01:22 UTC, merged