Ramona armando/20 consultar reporte de proyecto
Black-Dot-2024/Zeitgeist-Backend pull request #28
Opened 2024-04-09 19:53 UTC by ArmandoRosasB

Creacion del end-point: BASE_URL/api/v1/project/report/:id
Descripcion: Se retorna la informacion de un reporte de proyecto aceptado o en cotizacion
Se crearon/modificarion los siguientes archivos:
- index.route.ts
- project.routes.ts
- project.controller.ts
- project_report.services.ts
- project.repository.ts
- project.entity.ts

2024-04-09 21:36 UTC, DHurtado714-itesm commented
Van a tener que hacer un mapper para pasar del model de Prisma a la entity

este es un ejemplo

```typescript
import { employee } from '@prisma/client';
import { EmployeeEntity } from '../../domain/entities/employee.entity';

export function mapEmployeeEntityFromDbModel(model: employee): EmployeeEntity {
  return {
    id: model.id,
    firstName: model.first_name,
    lastName: model.last_name,
    email: model.email,
    phoneNumber: model.phone_number ? model.phone_number : undefined,
    imageUrl: model.image_url ? model.image_url : undefined,
    createdAt: model.created_at,
    updatedAt: model.updated_at ? model.updated_at : undefined,
    idDepartment: model.id_department ? model.id_department : undefined,
    idRole: model.id_role,
  };
}
```

2024-04-09 21:36 UTC, lCDSLl-Richard submitted a review, later dismissed

2024-04-09 21:36 UTC, lCDSLl-Richard commented on src/api/routes/project.routes.ts
> +router.get('/report/:id', getReportData);
No sería bueno especificar que el reporte es de un proyecto? Por si en un futuro tenemos más tipos de reporte. Algo tipo `/project/report/:id`. O incluso `/project/:id/report`. Igual habría que ver que rutas tienen los proyectos para mantener consistencia. Qué opinan?

2024-04-09 21:36 UTC, lCDSLl-Richard commented on src/core/infra/repositories/project.repository.ts
La lógica la veo bien, pero creo que está en el lugar incorrecto. Creo que este repositorio solo debería generar una consulta a la tabla de proyecto, y luego tendrían que crear el repositorio de tasks que saque las tasks, y debería ser el servicio el que sume las horas y haga toda esa lógica. Qué me corrija @DHurtado714-itesm si me equivoco.

2024-04-09 21:36 UTC, lCDSLl-Richard commented on src/index.ts
> +
Este espacio es a propósito? jaja

2024-04-09 21:38 UTC, DHurtado714-itesm requested changes

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/infra/repositories/project.repository.ts
Este metodo esta bastante extenso, deberiamos de volverlo en funciones mas pequeñas. Recomendacion hacer `getAll()`, `getById`, `getByUserId`, `create`, `update`, `delete`

Importante que no haya logica en el repositorio, tambien si quieren filtrar por un atributo muy epecifico, haganlo en el service

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/infra/repositories/project.repository.ts
> +import { randomUUID } from 'crypto';
si no se usa randomUUID, no lo pongan porfa

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/domain/entities/project.entity.ts
> +}
Revisar el estandar de comentario para las variables de las entidades

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/domain/entities/project.entity.ts
> +    matter?: string | null;
con el `?`, no es necesario usar `| null`

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/app/services/project_report.services.ts
> +    } catch (error: any) {
usar `unknown` preferiblemente

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/app/services/project_report.services.ts
> +async function getReport(id: string): Promise<Report> {
Aqui deberia de ir la logica

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/app/services/project_report.services.ts
> +export { getReport };
cambiar a export const ProjectReportService = { getReport }

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/app/services/project_report.services.ts
Cambiar el nombre a project-report.service.ts

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/api/controllers/project.controller.ts
> +export { getReportData };
mismo comment

2024-04-09 21:38 UTC, DHurtado714-itesm commented on src/core/domain/entities/project.entity.ts
Usar pascalCase para las variables

2024-04-09 21:39 UTC, DHurtado714-itesm commented on src/core/infra/repositories/project.repository.ts
+1 en esto

2024-04-09 21:39 UTC, DHurtado714-itesm commented on src/api/routes/project.routes.ts
> +router.get('/report/:id', getReportData);
+1

2024-04-09 21:59 UTC, ArmandoRosasB commented on src/api/routes/project.routes.ts
> +router.get('/report/:id', getReportData);
En el archivo index.route.ts esta el URL BASE que es project. En project_routes.ts esta todo lo relacionado a proyecto

2024-04-11 03:59 UTC, ArmandoRosasB commented
Creacion del end-point: BASE_URL/api/v1/project/report/:id
Descripcion: Se retorna la informacion de un reporte de proyecto 
Se crearon/modificarion los siguientes archivos despues de la retroalimentacion:

project-report.interface.ts
project-report.services.ts

company.entity.ts
employee-task.entity.ts
employee.entity.ts
project.entity.ts
task.entity.ts

company-entity-from-db-model-mapper.ts
employee-entity-from-db-model-mapper.ts
employee-task-entity-from-db-model-mapper.ts
project-entity-from-db-model-mapper.ts
task-entity-from-db-model-mapper.ts

company.repository.ts
employee-task.repository.ts
employee.repository.ts
project.repository.ts
tasks.repository.ts

2024-04-11 23:22 UTC, RodrigoTeran requested changes
Les puse algunos comentarios 😬

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/app/services/project-report.services.ts
> +    }
¿No sería mejor solo devolver el objeto sin crear una variable? Luego cuando los demás copien su ejemplo todos van a hacer lo mismo.

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/app/services/project-report.services.ts
> +        if (status.status !== 'In quotation' && status.status !== '-' && status.status !== 'Cancelled'){  // 'Accepted' 'Not started' 'In process' 'Under revision' 'Delayed' 'Postponed' 'Done'
En vez de hardcodear los strings mejor usen constantes. @DHurtado714-itesm ¿Desde dónde podrían crear las constantes `In quotation`, `Cancelled`, etc... para que se estandarice?

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/infra/mappers/company-entity-from-db-model-mapper.ts
> +  return {
¿@DHurtado714-itesm no crees que está de más poner `FromDBModel`?
Creo que se entiende... solo hace más verboso el código...

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/infra/repositories/employee-task.repository.ts
> +    let data = await Prisma.employee_task.findMany({});
No es necesario que le pongan las llaves adentro al `findMany()`

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/infra/repositories/employee-task.repository.ts
> +async function findAll(): Promise<EmployeeTask[]> {
Poner un `try {} catch {}`porfa

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/infra/repositories/project.repository.ts
> +async function findProjectStatusById(id: string) {
Igual en estas dos funciones... `findProjectStatusById` y `findById` poner `try {} catch {}`

2024-04-11 23:22 UTC, RodrigoTeran commented on src/core/infra/repositories/tasks.repository.ts
> +async function findTasksByProjectId (id_project: string) : Promise<Task[]> {
Poner un `try {} catch {}`porfa

2024-04-12 15:44 UTC, DHurtado714-itesm requested changes

2024-04-12 15:44 UTC, DHurtado714-itesm commented on src/core/app/services/project-report.services.ts
> +        if (status.status !== IN_QUOTATION && status.status !== WITHOUT_STATUS && status.status !== CANCELLED){  // 'Accepted' 'Not started' 'In process' 'Under revision' 'Delayed' 'Postponed' 'Done'
export enum ReportStatus {
    ....
}

Aqui seria ReportStatus.IN_QUOTATION, etc.

2024-04-12 15:44 UTC, DHurtado714-itesm commented on src/core/infra/repositories/company.repository.ts
> +async function findById(id: string): Promise<Company> {
Nice !!

2024-04-13 00:46 UTC, DHurtado714-itesm approved these changes

2024-04-13 00:51 UTC, salgue441 approved these changes

2024-04-13 00:56 UTC, merged