Feat/test
Black-Dot-2024/Zeitgeist-Backend pull request #29
Opened 2024-04-09 21:40 UTC by salgue441

# Description 

Added new dummy.repository.test.ts

2024-04-09 21:55 UTC, lCDSLl-Richard commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
No solo íbamos a testear servicios y no repositorios? Además, aquí no controlamos el valor de las cosas, entonces no podríamos testear algo cómo un filtro del repositorio, porque estaríamos usando daros de la base de datos real.

2024-04-10 03:21 UTC, DHurtado714-itesm commented
Pushea a develop

2024-04-10 03:29 UTC, DHurtado714-itesm requested changes

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/api/controllers/dummy.controller.ts
Actualiza tu rama con los cambios de develop plis

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/api/routes/dummy.routes.ts
Esto tambien

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
Si tienes un punto muy valido, lo unico que me preocupa es que se devuelva un formato correcto y coherente de los repositorios

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
> +      const result = await findAll();
Actualiza la rama y renombra este metodo

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
> +        expect(dummy.id).to.match(/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}/);
Busca si existe un metodo que valide si es UUID. Evitemonos el regex

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
> +      };
No se supone que el error deberia de ser generado en la capa de repositorio. Aqui la situacion seria validar si el codigo tira el error o no

2024-04-10 03:29 UTC, DHurtado714-itesm commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
> +        expect(error.message).to.equal('An unexpected error occurred');
Precisamente esto

2024-04-10 03:29 UTC, DHurtado714-itesm commented on tsconfig.test.json
> +    "outDir": "./dist-test",
Porque estamos compilando a otro dist? si es necesario?

2024-04-10 21:19 UTC, salgue441 commented on tsconfig.test.json
> +    "outDir": "./dist-test",
Es por buenas prácticas, pero lo puedo cambiar al dist normal

2024-04-10 21:19 UTC, salgue441 commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
> +      };
Es que tenía que tirarlo de alguna manera hahah

2024-04-10 21:28 UTC, salgue441 commented on src/core/infra/repositories/__tests__/dummyRepository.spec.ts
> +        expect(dummy.id).to.match(/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}/);
Hay una librería, pero no lo veo necesario importar una librería completa solo para un validate.

2024-04-11 04:53 UTC, DHurtado714-itesm commented on tsconfig.test.json
> +    "outDir": "./dist-test",
si cambialo mejor a dist normal para no complicarnos

2024-04-12 03:27 UTC, DHurtado714-itesm approved these changes

2024-04-12 03:27 UTC, merged