Teran perdomo/24 modificar rol usuario
Black-Dot-2024/Zeitgeist-Backend pull request #35
Opened 2024-04-12 22:48 UTC by RodrigoTeran

# User Story

| US ID | Module | User Story                                                                  | System  | Priority | Size | Testing | Documentation |
| ----- | ------ | --------------------------------------------------------------------------- | ------- | -------- | ---- | ------- | ------------- |
| 24   | ADMIN   | Editar el rol de un usuario | Backend | High     | M    | In-progress    | [ ]           |

### Description

Como administrador quiero editar el rol de los usuarios

### Acceptance Criteria

- [X] El sistema permite actualizar el rol del usuario.

2024-04-12 22:50 UTC, RodrigoTeran commented
Tenemos varias dudas... pero igual ya vamos haciendo el PR para que lo vayan checando...

Como solo un administrador puede cambiar los roles, necesitamos saber cómo checarlo.
- ¿Solo checamos que el rol del usuario que está haciendo el request sea admin?
- ¿Ya está la parte de auth?
- ¿Está el control de acceso basado en roles?
- ¿Un admin no puede cambiarse su mismo rol?

2024-04-12 22:51 UTC, salgue441 commented
Si quieres ver las pruebas de service, https://github.com/Black-Dot-2024/Zeitgeist-Backend/blob/Flores-Salguero/23-eliminar-empresa/src/core/app/services/__tests__/company.service.spec.ts

2024-04-12 22:55 UTC, salgue441 requested changes

2024-04-12 22:55 UTC, salgue441 commented on src/api/controllers/admin.controller.ts
> +        res.status(200).json({ data: null });
Porque null?

2024-04-12 22:55 UTC, salgue441 commented on src/api/routes/admin.routes.ts
> +router.put("/rol", updateUserRol);
la ruta debería ser role para que todo esté en inglés

2024-04-12 22:57 UTC, RodrigoTeran commented on src/api/controllers/admin.controller.ts
> +        res.status(200).json({ data: null });
Vamos a devolver el objeto de Employee actualizado

2024-04-12 22:57 UTC, RodrigoTeran commented on src/api/routes/admin.routes.ts
> +router.put("/rol", updateUserRol);
Jeje, vamos

2024-04-14 05:13 UTC, lCDSLl-Richard requested changes

2024-04-14 05:13 UTC, lCDSLl-Richard commented on db/tests/getRoles.sql
Vamos a testear la db con SQL directamente? Según recuerdo esto no estaba en el plan de calidad.

2024-04-14 05:13 UTC, lCDSLl-Richard commented on src/api/controllers/admin.controller.ts
> +interface IUpdateUserRolBody {
Estámos usando el estándar tipo C# o Java de poner la I en interfaces? Creo que nadie más lo está haciendo.

2024-04-14 05:13 UTC, lCDSLl-Richard commented on src/api/controllers/admin.controller.ts
> +        };
Esto valdría la pena cambiarlo por zod, no?

2024-04-14 05:13 UTC, lCDSLl-Richard commented on src/api/controllers/admin.controller.ts
> +export { updateUserRol };
Veo que no hay newline al final del archivo, si están usando prettier?

2024-04-14 05:13 UTC, lCDSLl-Richard commented on src/core/domain/entities/employee.entity.ts
> +export interface EmployeeEntity {
Cuál es el estándar aquí? Veo entidades que solo se llaman como la tabla, y entidades que tienen el nombre + `Entity`

2024-04-14 05:13 UTC, lCDSLl-Richard commented on src/core/infra/repositories/employee.repository.ts
> +    } catch (error: unknown) {
No hay que hacer catch del error si no se va a usar en el bloque catch.

2024-04-14 16:34 UTC, DHurtado714-itesm requested changes

2024-04-16 00:52 UTC, DiegoPerdomoS commented on src/core/domain/entities/employee.entity.ts
> +export interface EmployeeEntity {
El estandar seria nombre+Entity

2024-04-16 00:56 UTC, DiegoPerdomoS commented on db/tests/getRoles.sql
Andabamos probando nomas jaja

2024-04-16 01:23 UTC, DiegoPerdomoS commented on src/api/controllers/admin.controller.ts
> +interface IUpdateUserRolBody {
Listo ya lo quite

2024-04-16 21:09 UTC, lCDSLl-Richard requested changes

2024-04-16 21:09 UTC, lCDSLl-Richard commented on src/api/routes/admin.routes.ts
No veo newLine al final del archivo, recuerden usar el formateador

2024-04-16 21:09 UTC, lCDSLl-Richard commented on src/core/app/services/admin-role.services.ts
> +export { updateUserRole as updateUserRole };
Es necesario el `as`?

2024-04-18 21:49 UTC, RodrigoTeran commented
@lCDSLl-Richard @DHurtado714-itesm @salgue441 Ya para hacerle merge y ya cuando estén los PR que este requisito depende de, creamos su PR de `fix`

2024-04-18 21:50 UTC, salgue441 approved these changes

2024-04-20 00:51 UTC, DHurtado714-itesm reviewed
Some general comments on docuementation, fix this and it's good to go

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/api/controllers/admin.controller.ts
> +
Missing docuementation

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/api/controllers/admin.controller.ts
> +    // Validating request body against the schema
Delete internal comments

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/api/controllers/admin.controller.ts
> +    // Connect with service
Delete internal comments

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/api/controllers/admin.controller.ts
> +    // Handling Zod errors or other types of errors
Delete internal comments

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/core/app/services/admin-role.services.ts
> +    // Update User role
Delete internal comments

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/core/app/services/admin-role.services.ts
> +async function updateUserRole(userId: string, roleId: string): Promise<EmployeeEntity> {
Comment code

2024-04-20 00:51 UTC, DHurtado714-itesm commented on src/core/domain/entities/employee.entity.ts
> +
Delete this, we are not going to use it

2024-04-22 20:52 UTC, ArmandoRosasB approved these changes

2024-04-22 21:00 UTC, merged