RF47: Iniciar sesion
Black-Dot-2024/Zeitgeist-Backend pull request #37
Opened 2024-04-14 19:33 UTC by DHurtado714-itesm

# User Story

| US ID | Module | User Story                                                                  | System  | Priority | Size | Testing | Documentation |
| ----- | ------ | --------------------------------------------------------------------------- | ------- | -------- | ---- | ------- | ------------- |
| 47   | AUTH   | Iniciar sesion con google auth | web | High     | 21    | Done    | [ ]           |

### Description

Se crea un endpoint para crear un nuevo empleado y valida los inputs

### Acceptance Criteria

- [x] Visualizar la lista de los servicios disponibles para proveedores dentro de la app móvil
- [] Marcar los servicios que ofrece su empresa
- [] Continuar con la subida de documentos en la siguiente vista

## UI Design (or Program Flow)

<img width="1138" alt="Screenshot 2024-04-14 at 13 27 37" src="https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/81983296/c09ee4b2-1be1-4119-bd37-c2ad1d521b37">

<img width="1139" alt="Screenshot 2024-04-14 at 13 27 02" src="https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/81983296/a141d53e-c745-4da5-ac07-7bcc157e265d">

2024-04-14 19:39 UTC, sebFlores02 submitted a review, later dismissed

2024-04-16 12:23 UTC, salgue441 requested changes

2024-04-16 12:23 UTC, salgue441 commented on src/api/controllers/employee.controller.ts
> +      return res.status(400).json({ message: 'Validation error', errros: parsedBody.error.issues });
Tienes un typo en errors

2024-04-16 12:23 UTC, salgue441 commented on src/api/controllers/employee.controller.ts
> +  firstName: z.string().min(1, { message: 'First name cannot be empty' }),
Mi recomendación seria también poner un mínimo que haga match con la longitud de la base de datos pata evitar esa validación en otra capa y que la data sea consistente

2024-04-16 12:23 UTC, salgue441 commented on src/api/routes/employee.routes.ts
> +router.post('/create', checkAuthToken, EmployeeController.createUser);
Te falta la documentación de swagger, no?

2024-04-16 12:23 UTC, salgue441 commented on src/core/app/services/employee.service.ts
> +  const role = await RoleRepository.findByTitle(SupportedRoles.SIN_ROL);
Para mantener todo en inglés, el SIN_ROL debería ser WITHOUT_ROLE

2024-04-16 12:24 UTC, salgue441 commented
Para que pasen los tests de GHA, añade la firebase key en los secretos

2024-04-16 21:07 UTC, lCDSLl-Richard submitted a review, later dismissed

2024-04-16 23:21 UTC, OlimpiaGarcia commented on prisma/schema.prisma
no deberia ser en ingles?

2024-04-16 23:21 UTC, OlimpiaGarcia commented on src/core/infra/mappers/role-entity-from-db-model.mapper.ts
sin rol en ingles?

2024-04-16 23:21 UTC, OlimpiaGarcia commented on src/utils/enums/index.ts
aqui esta el origen del SIN_ROL

2024-04-18 20:41 UTC, sgarnica1 submitted a review, later dismissed

2024-04-18 21:12 UTC, OlimpiaGarcia submitted a review, later dismissed

2024-04-18 21:27 UTC, salgue441 approved these changes

2024-04-18 21:28 UTC, merged