Fix github actions
Black-Dot-2024/Zeitgeist-Backend pull request #38
Opened 2024-04-14 20:17 UTC by DHurtado714-itesm

2024-04-15 00:40 UTC, lCDSLl-Richard commented on .github/workflows/production.yml
> +          pm2 reload all
No deberíamos hacer reload de solo Prod? Y no cambiamos el nombre del directorio a prod o algo así? Para poder clonar staging también.

2024-04-15 01:00 UTC, DHurtado714-itesm commented on .github/workflows/production.yml
> +          pm2 reload all
Cambie el nombre de staging. Y si tienes razon hago los cambios

2024-04-15 23:26 UTC, RodrigoTeran requested changes

2024-04-15 23:26 UTC, RodrigoTeran commented on .github/workflows/develop.yml
> +      - name: SetU up Node.js
Corregir falta de ortografía

2024-04-15 23:26 UTC, RodrigoTeran commented on .github/workflows/production.yml
> +      - name: Install pnpm
Para ser consistentes... ¿aquí no sería ```Install PNPM```?

2024-04-15 23:56 UTC, DHurtado714-itesm reviewed
fix(PR): fix comments

2024-04-16 00:19 UTC, salgue441 approved these changes

2024-04-16 00:24 UTC, merged