Feat/rf27 consultar clientes
Black-Dot-2024/Zeitgeist-Backend pull request #45
Opened 2024-04-16 23:17 UTC by sgarnica1

## RF27 Consultar los clientes

[Feature/Task ID]: Obtener una lista de todos los clientes

### Descripción

Se obtiene una lista de todos los clientes y se calculan sus proyectos totales, las horas cobrables, las horas cobrables de legal y las horas cobrables de contable

### Cambios realizados

- company.entity.ts
- company.repository.ts
- company-entity-from-db-model.mapper.ts
- company.services.ts
- company.controller.ts
- company.routes.ts
- project.entity.ts
- project.repository.ts
- project-entity-from-db-model.mapper.ts

Se modificaron los siguientes archivos:
- index.routes.ts

### Story Points

8

### Pruebas

Describe la prueba unitaria de pruebas utilizada para este cambio. Incluye detalles sobre pruebas unitarias, pruebas de integración, pruebas de aceptación y cualquier manual realizado.

### Criterios de aceptación
- [x] El sistema muestra una lista de los de todos los clientes no archivados registrados en la plataforma por orden alfabético. 
- [x] El sistema muestra la siguiente información del usuario: nombre, horas del área contable, horas del área legal, horas cobrables, proyectos totales
- [x] El sistema muestra una opción para agregar un nuevo cliente
- [x] El sistema muestra una opción para mostrar los clientes archivados y no archivados

### Dependencias

Ninguno

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### Notas Adicionales

Cualquier información adicional que el revisor o el autor del PR necesite saber. Aquí es donde se puede incluir imagenes, gifs, etc.

2024-04-17 21:03 UTC, salgue441 commented on .github/actions/staging.yml
> +          target: '/path/to/your/app'
Cambiar al path actual donde se encuentren los contenidos de la aplicación.

2024-04-17 21:04 UTC, salgue441 commented on .github/actions/staging.yml
> +        run: npm install -g pnpm
Como recomendación, se debería a cambiar a instalar pnpm y dependencias una vez y luego hacer que revise si ya existen para no estar intentando instalar cada vez.

2024-04-17 21:09 UTC, salgue441 commented on src/core/infra/mappers/project-entity-from-db-model.mapper.ts
Estandarizar un solo mapper para no tener archivos duplicados

2024-04-17 21:10 UTC, salgue441 commented on src/index.ts
> +    origin: 'http://localhost:3000',
Pon el puerto como variable y no hardcoded

2024-04-18 03:59 UTC, DHurtado714-itesm commented
Acutualiza tu rama con develop, hay cosas que ya estan en develop y las marca como cambios

2024-04-18 03:59 UTC, DHurtado714-itesm requested changes

2024-04-18 03:59 UTC, DHurtado714-itesm commented on .github/actions/staging.yml
> +          target: '/path/to/your/app'
Yo ya hice estos cambios, no se porque no te da conflictos

2024-04-18 19:13 UTC, sgarnica1 commented on src/api/controllers/company.controller.ts
> +import { CompanyService } from '../../core/app/services/company.services';
Validación de lo que recibo de la BD? Porque en este caso no envía nada el cliente

2024-04-18 19:15 UTC, sgarnica1 commented on .github/actions/staging.yml
> +        run: npm install -g pnpm
Voy a eliminar la carpeta de .github/actions

2024-04-18 19:15 UTC, sgarnica1 commented on src/api/controllers/project.controller.ts
Mismo que arriba, valido lo que venga de la DB?

2024-04-18 19:25 UTC, sgarnica1 commented on src/index.ts
> +    origin: 'http://localhost:3000',
Voy a añadir una variable de entorno

2024-04-18 19:29 UTC, sgarnica1 commented on src/core/infra/mappers/company-entity-from-db-model.mapper.ts
Listo

2024-04-18 19:30 UTC, sgarnica1 commented on src/index.ts
> +    origin: 'http://localhost:3000',
Listo

2024-04-22 02:44 UTC, ArmandoRosasB commented on .env.example
> -NODE_ENV="development"
El .env.example aun ese necesario? Es pregunta. Para ver si es mejro que ya se elimine y que cada quien tenga su .env

2024-04-22 03:38 UTC, ArmandoRosasB commented on src/core/domain/entities/project.entity.ts
> +export interface ProjectEntity {
Documentacion de la entidad

2024-04-22 03:38 UTC, ArmandoRosasB commented on src/core/domain/entities/company.entity.ts
> +export interface CompanyEntity {
Documentacion de al entidad

2024-04-22 04:12 UTC, sgarnica1 commented on .env.example
> -NODE_ENV="development"
Yo creo que ya podemos eliminarlo

2024-04-22 04:30 UTC, sgarnica1 commented on src/core/domain/entities/project.entity.ts
> +export interface ProjectEntity {
Listo

2024-04-22 04:31 UTC, sgarnica1 commented on src/core/domain/entities/company.entity.ts
> +export interface CompanyEntity {
Listo

2024-04-22 04:45 UTC, ArmandoRosasB approved these changes

2024-04-22 23:50 UTC, salgue441 requested changes

2024-04-22 23:50 UTC, salgue441 commented on src/core/domain/entities/company.entity.ts
> + * @brief Esta clase es para establecer la estructura de la entidad company
Comentarios en inglés

2024-04-22 23:54 UTC, sgarnica1 commented on src/core/domain/entities/company.entity.ts
> + * @brief Esta clase es para establecer la estructura de la entidad company
Listo

2024-04-23 00:33 UTC, salgue441 approved these changes

2024-04-23 00:35 UTC, ArmandoRosasB approved these changes

2024-04-23 00:44 UTC, DHurtado714-itesm approved these changes
Necesitamos hacer unos cambios, pero ya mejor hacer merge porque esta muy grande

2024-04-23 00:44 UTC, merged