Feat/rf19 crear cliente
Black-Dot-2024/Zeitgeist-Backend pull request #52
Opened 2024-04-22 22:36 UTC by sgarnica1

## Pull Request Titulo

[Feature/Task ID]: Add new client

### Descripción

Enpoint for creating a new client

### Cambios realizados

- company.routes.ts
- company.controller.ts
- company.service.ts
- company.repository.ts
- company.entity.ts
- company.service.test.ts

### Story Points

10

### Pruebas
Unit test for creating a new company

![image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/71858836/b8ef01cf-1aee-4897-9700-83235ed993b8)

### Criterios de aceptación

El backend permite al frontend cumplir con los siguientes criterios de aceptación

[ ] El sistema permite al usuario seleccionar la opción de crear un nuevo cliente
[ ] El sistema permite ingresar el nombre del cliente que se quiere agregar.
[ ] El sistema verifica que el campo esté completo
[ ] El sistema muestra un mensaje de éxito o error dependiendo del status.
[ ] El sistema redirige al usuario del sistema a una pantalla con la vista de todos los clientes

### Dependencias

[PR27 Consultar Clientes](https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/45)

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/core/app/services/project-report.services.ts
los comentarios deben ir en inglés

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/core/domain/entities/company.entity.ts
> + * @brief Esta clase es para establecer la estructura de la entidad company
comments en inglés

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/core/domain/entities/employee-task.entity.ts
comments en inglés

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/core/domain/entities/project.entity.ts
> + * @param totalHours: Deciaml
decimal

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/core/domain/entities/project.entity.ts
comments en inglés

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/core/domain/entities/task.entity.ts
comments n ingles

2024-04-23 00:06 UTC, OlimpiaGarcia commented on src/index.ts
> -  	// origin: "*",
esto que esta comentado. se usa??

2024-04-24 06:16 UTC, OlimpiaGarcia commented on src/core/app/services/company.services.ts
> +          if (project.area == SupportedDepartments.CONTABLE)
contable no existe, es accounting

2024-04-26 05:58 UTC, sgarnica1 commented on src/core/app/services/company.services.ts
> +          if (project.area == SupportedDepartments.CONTABLE)
Listo

2024-04-26 06:07 UTC, sgarnica1 commented on src/core/domain/entities/task.entity.ts
Listo

2024-04-26 06:12 UTC, sgarnica1 commented on src/core/app/services/__tests__/project.service.test.ts
>            id: randomUUID(),
Se necesitan para el test

2024-04-26 16:16 UTC, DHurtado714-itesm requested changes

2024-04-26 16:16 UTC, DHurtado714-itesm commented on src/api/middlewares/rbac.middleware.ts
No necesitas usar el try catch, porque el service arroja el error si pasa algo inesperado

2024-04-26 16:16 UTC, DHurtado714-itesm commented on src/api/routes/company.routes.ts
Ya no es necesario usar @openapi

2024-04-26 16:16 UTC, DHurtado714-itesm commented on src/api/routes/project.routes.ts
hay que usar el auth middleware y el rbac tambien

2024-04-26 16:16 UTC, DHurtado714-itesm commented on src/core/infra/repositories/company.repository.ts
> +        id: randomUUID(),
Este random UUID debe de crearse desde el service

2024-04-26 16:16 UTC, DHurtado714-itesm commented on src/core/infra/repositories/company.repository.ts
> +        created_at: new Date(),
Tambien la fecha

2024-04-26 16:16 UTC, DHurtado714-itesm commented on src/core/infra/repositories/project.repository.ts
> +    console.log(error);
Elimina el console.log

2024-04-26 22:11 UTC, OlimpiaGarcia commented on src/api/routes/company.routes.ts
> +  checkAuthRole([SupportedRoles.CONTABLE, SupportedRoles.LEGAL, SupportedRoles.ADMIN]),
no es contable, es accounting

2024-04-26 22:36 UTC, sgarnica1 commented on src/core/infra/repositories/company.repository.ts
> +        id: randomUUID(),
Listo

2024-04-28 01:53 UTC, OlimpiaGarcia approved these changes

2024-04-28 01:53 UTC, OlimpiaGarcia approved these changes
listo!, solo cierra tus issues del defect log

2024-04-29 01:30 UTC, DHurtado714-itesm approved these changes

2024-04-29 01:30 UTC, merged