RF12: Crear un proyecto
Black-Dot-2024/Zeitgeist-Backend pull request #75
Opened 2024-04-24 00:57 UTC by lCDSLl-Richard

## Pull Request Titulo

[RF12]: Crear un proyecto nuevo

### Descripción

Creación de un endpoint y validación para crear un nuevo proyecto desde el front-end.

### Cambios realizados

- Añadir ruta para crear proyectos
- Añadir parsing para validar el body de la request
- Crear enums para todos los campos del proyecto
- Crear tests para mi endpoint

### Story Points

13

### Pruebas

El servicio unicamente pasa los datos al respositorio, por lo que únicamente se testea esta funcionalidad

### Criterios de aceptación

- [ ] Al seleccionar la opción de registrar nuevo proyecto el sistema enseña un formulario con datos a llenar sobre el nuevo proyecto: <ul>
    <li>Nombre del proyecto</li>
    <li>Cliente</li>
    <li>Matter</li>
    <li>Categoría</li>
    <li>Fecha de inicio</li>
    <li>Fecha de finalización</li>
    <li>Descripción</li>
    <li>Cobrable</li>
    <li>Periódico</li>
    <li>Área (legal/accountable)</li>
</ul>
- [ ] El sistema debe validar que todos los campos estén completos y que sea del tipo especificado en el diccionario de datos.
- [ ] El sistema debe permitir al colaborador seleccionar la opción para guardar la información del proyecto y registrarlo.
- [ ] Después de registrar el proyecto, el sistema muestra un mensaje de éxito y actualiza los proyectos.

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### Notas Adicionales

2024-04-25 22:54 UTC, lCDSLl-Richard commented on src/api/controllers/project.controller.ts
>  async function getReportData(req: Request, res: Response) {
La función no es de este pr.

2024-04-26 00:23 UTC, DHurtado714-itesm requested changes

2024-04-26 00:46 UTC, OlimpiaGarcia approved these changes

2024-04-27 02:37 UTC, DHurtado714-itesm approved these changes

2024-04-27 02:38 UTC, merged