Yuna/rf22
Black-Dot-2024/Zeitgeist-Backend pull request #95
Opened 2024-04-26 06:46 UTC by OlimpiaGarcia

## Pull Request Titulo

[Feature/Task ID]: Descripción del cambio

### Descripción

Descripción clara y concisa de los cambios realizados. Incluye el contexto relevante, como historias de usuario o criterios de aceptación.

### Cambios realizados

- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.

### Story Points

Estima la complejidad de la tarea en puntos de historia.

### Pruebas

Describe la prueba unitaria de pruebas utilizada para este cambio. Incluye detalles sobre pruebas unitarias, pruebas de integración, pruebas de aceptación y cualquier manual realizado.

### Criterios de aceptación

Describe los criterios que deben cumplirse para que este PR sea aceptado. Esto debe estar alineado con la historia de usuario o tarea original.

### Dependencias

Enumera cualquier dependencia o PR relacionado que deba fusionarse antes o después de este PR.

### Definición de Done

- [ ] El código ha sido revisado por al menos un miembro del equipo.
- [ ] Todas las pruebas pasan localmente.
- [ ] El código sigue los estándares de codificación y las mejores prácticas del proyecto.
- [ ] La documentación ha sido actualizada (si corresponde).
- [ ] Cualquier nueva dependencia está documentada y justificada.
- [ ] Los cambios han sido probados en un entorno de preparación (si corresponde).

### Notas Adicionales

Cualquier información adicional que el revisor o el autor del PR necesite saber. Aquí es donde se puede incluir imagenes, gifs, etc.

2024-04-27 18:33 UTC, salgue441 requested changes

2024-04-27 18:33 UTC, salgue441 commented on package.json
> +    "ts-mockito": "^2.6.1",
Eliminar esta dependencia

2024-04-27 18:33 UTC, salgue441 commented on src/api/routes/employee.routes.ts
> +router.delete('/delete/:id', EmployeeController.deleteEmployee);
Falta el Middleware de auth

2024-04-27 20:20 UTC, DHurtado714-itesm requested changes

2024-04-27 20:20 UTC, DHurtado714-itesm commented on src/api/routes/employee.routes.ts
> +router.delete('/delete/:id', EmployeeController.deleteEmployee);
y RBAC

2024-04-27 20:20 UTC, DHurtado714-itesm commented on src/api/controllers/employee.controller.ts
> +    console.error('Error: ', error);
No es necesario

2024-04-27 20:20 UTC, DHurtado714-itesm commented on src/api/controllers/employee.controller.ts
> +    console.error('Error: ', error);
No es necesario

2024-04-27 20:20 UTC, DHurtado714-itesm commented on src/core/app/services/employee.service.ts
> + */
Seguir el formato de doxygen

2024-04-27 20:20 UTC, DHurtado714-itesm commented on src/core/app/services/employee.service.ts
> +    console.log('Error: ', error);
Esto deberia de eliminarse

2024-04-27 20:20 UTC, DHurtado714-itesm commented on src/core/infra/repositories/employee.repository.ts
> +    console.log(error);
Esto deberia de eliminarse

2024-04-28 02:43 UTC, DHurtado714-itesm approved these changes

2024-04-28 20:02 UTC, salgue441 approved these changes

2024-04-28 20:04 UTC, merged